### ISSUE TITLE
Discovery: Local development discovery

### ISSUE THREAD

**Issue by rgraber** [edx/devenv-wg#1]
1. Determine if the current discovery plugin is sufficient for local development or, if not, what it will require to be so
2. If necessary, create issues with Tutor or 2u to address any gaps with the plugin
3. Document how to develop with discovery locally for 2u engineers

**Comment by zacharis278** [comment]
There is one issue that's pretty easy to get around, I've opened a ticket to look into that further: https://github.com/edx/devenv-wg/issues/13

Set up instructions here: https://openedx.atlassian.net/wiki/spaces/AC/pages/3399221333/Tutor+Developing+with+Course+Discovery
