### ISSUE TITLE
Review/pull down Plugin v1 API PR

### ISSUE THREAD

**Issue by rgraber** [edx/devenv-wg#12]
Pull down the code in this PR and make sure we can still run the discovery and MFE plugins and do all the things we currently do (bind-mounts, etc). Feel free to experiment around with creating new v1 plugins that you think will help your dev workflow. 
https://github.com/overhangio/tutor/pull/599

**Comment by zacharis278** [comment]
I've tested these changes as backward compatible with the current plugins. The upgrade path for plugins is fairly straightforward, v1 is mostly additive in features: https://discuss.overhang.io/t/how-to-upgrade-a-tutor-plugin/1488

Upgrades for the plugins we care most about (mfe, disco, ecom) are either done or in-progress: https://edx-internal.slack.com/archives/C01AGTSB1LL/p1652803881776849
