### ISSUE TITLE
Discovery: how can we reduce repetitive steps setting up development venv and docker volume?

### ISSUE THREAD

**Issue by zacharis278** [edx/devenv-wg#15]
There are a bunch of manual tasks to get a IDA set up in 'dev' mode. Doing this individually for each service and MFE is cumbersome and a lot of this configuration is buried in a tutor application folder.

Maybe a plugin that is bit opinionated about the folder structure?

Regis recently made improvements to bindmount. Does this help us?

**Comment by rgraber** [comment]
This duplicates work in [wg-developer-experience](https://github.com/openedx/wg-developer-experience)
