### ISSUE TITLE
e2e event bus in Tutor

### ISSUE THREAD

**Issue by rgraber** [edx/devenv-wg#17]
A/C

- [ ] As a developer, I am able to produce and consume events using the event-bus-kafka plugin across different services (in particular, studio and course-discovery) in a Tutor environment
- [ ] As a developer, I am able to do development work on event-bus-kafka within the Tutor environment

**Comment by rgraber** [comment]
Currently struggling with getting course-discovery to start up at all. I keep getting `ModuleNotFoundError: No module named 'config_models'.` When I try to `make requirements`, it ends up uninstalling django and that crashes the whole container. This feels like a job for mounted venvs but those have the issue where I can't actually use the same venv in both the container and my local setup because the $PATH will be different.

**Comment by zacharis278** [comment]
@rgraber any reason you need to access the venv that you are using with tutor locally? I've generally just been booting up the container in a shell (without starting the actual service) to do any messing around in the env or installing reqs that would normally cause django to crash out on startup.

basically just this:
```
tutor dev run myservice \
	  -m myservice:$HOME/workspace/myservice:/openedx/myservice \
	  -m myservice:$HOME/tutor-venvs/venv-myservice:/openedx/venv \
	  /bin/bash
```

**Comment by rgraber** [comment]
Oooh that's cute. I didn't think of using a run container.

**Comment by rgraber** [comment]
Update: using the run container worked. I'm able to produce events to a local Kafka broker that I set up as a plugin. I'm having trouble getting the event-bus-kafka library to play nicely with Discovery in Tutor.

**Comment by rgraber** [comment]
This has been moved to https://github.com/openedx/wg-developer-experience/issues/131
